package com.chatlycode.problem.domain;

public enum ProblemType {
    LAYER_VIOLATION,
    ENTITY_LEAK,
    GOD_SERVICE,
    HUGE_CLASS,
    HUGE_METHOD,
    CIRCULAR_DEPENDENCY,
    NO_TESTS,
    DEAD_CODE,
    TOO_MANY_DEPENDENCIES,
    GENERIC_NAME,
    HIGH_BLAST_RADIUS,
    DEBUG_ARTIFACT,
    TODO_MARKER,
    PANIC_USAGE,
    SECRET_EXPOSURE,
    HARDCODED_ENDPOINT,
    ASYNC_LOCK_HOTSPOT,
    BOUNDARY_VIOLATION,
    DUMPING_GROUND,
    LARGE_FILE,
    LONG_FUNCTION,
    UNRESOLVED_IMPORT
}
